import "./globals.css";
import Link from "next/link";
import Home from "./Home/page";

import Client from "./Client";
import Providers from "./Providers";
import Footer from "./Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap"
          rel="stylesheet"
        />

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/tw-elements.min.css"
        />

        <script src="https://cdn.tailwindcss.com/3.3.0"></script>
      </head>
      <html lang="en">
        <body style={{ backgroundColor: "#f1f3f8" }}>
          <Providers>
            <Client />
            {children}
          </Providers>
          <Footer />
        </body>
      </html>
    </>
  );
}
